- name: Restore VM Backup
  hosts: "{{ backup_hosts }}"
  vars:
    backup_hosts: "{{ update_hosts if update_hosts is defined else 'all' | default('all') }}"
  gather_facts: no
  roles:
  - rsoliman.azure_demos.azure_restore_backup
  