namespace: rsoliman
name: azure_demos
version: 1.0.0
readme: README.md
authors:
- Raed Soliman <raedrizk@gmail.com>

description: A collection of roles used to demo Azure automation using Ansible.

license:
- "MIT"

tags: ['Microsoft', 'Azure', 'demo','ansible','raedrizk','rsoliman']

dependencies:
    "azure.azcollection": "*"
    "ansible.builtin": "*"

repository: http://example.com/repository
homepage: http://example.com
issues: http://example.com/issue/tracker
