---
# tasks file for azure-tag-virtualmachine
- name: Add tag {{ azure_virtualmachine_tag_name }} to VM {{ azure_virtualmachine_name }}
  azure_rm_virtualmachine:
    resource_group: "{{ azure_resourcegroup_name }}"
    name: "{{ azure_virtualmachine_name }}"
    tags:
      "{{ azure_virtualmachine_tag_name }}": "{{ azure_virtualmachine_tag_value }}"
    append_tags: true
