---
- name: Create a Daily VM backup policy
  azure.azcollection.azure_rm_backuppolicy:
    vault_name: "{{ azure_recovery_services_vault_name }}"
    name: "{{ azure_backup_policy_name }}"
    resource_group: "{{ azure_resourcegroup_name }}"
    state: "{{ azure_backup_policy_state }}"
    backup_management_type: "AzureIaasVM"
    schedule_run_frequency: "Daily"
    instant_recovery_snapshot_retention: 1
    daily_retention_count: 1
    time_zone: "Easterm Standard Time"
    schedule_run_time: "{{ azure_backup_policy_run_hour }}"
  register: backuppolicy

- name: debug
  ansible.builtin.debug:
    var: backuppolicy

- name: Setting stats for the policy
  ansible.builtin.set_stats:
    data:
      backuppolicy: "{{ backuppolicy }}"
      azure_backup_policy_name: "{{ azure_backup_policy_name }}"
    aggregate: yes
  when: azure_backup_policy_state == 'present'

