---
# tasks file for azure-create-subnet
- name: Add subnet {{ azure_subnet_name }} to virtual network {{ azure_virtualnetwork_name }}
  azure_rm_subnet:
    resource_group: "{{ azure_resourcegroup_name }}"
    name: "{{ azure_subnet_name }}"
    address_prefix: "{{ azure_subnet_address_prefix }}"
    virtual_network: "{{ azure_virtualnetwork_name }}"