---
- name: Manage Azure Recovery Services vault
  azure.azcollection.azure_rm_recoveryservicesvault:
    resource_group: "{{ azure_resourcegroup_name }}"
    name: "{{ azure_recovery_services_vault_name }}"
    location: "{{ azure_recovery_services_vault_location }}"
    state: "{{ azure_recovery_services_vault_state }}"
  register: recoveryservicesvault

- name: debug
  ansible.builtin.debug:
    var: recoveryservicesvault

- name: Setting stats for the vault
  ansible.builtin.set_stats:
    data:
      recoveryservicesvault: "{{ recoveryservicesvault }}"
      azure_recovery_services_vault_name: "{{ azure_recovery_services_vault_name }}"
    aggregate: yes
  when: azure_recovery_services_vault_state == 'present'

