---
# tasks file for azure-create-networksecuritygroup
- name: manage Network Security Group {{ azure_securitygroup_name }} that allows SSH and WinRM over HTTPS in {{ azure_resourcegroup_name }}, and additional ports
  azure_rm_securitygroup:
    resource_group: "{{ azure_resourcegroup_name }}"
    name: "{{ azure_securitygroup_name }}"
    state: "{{ azure_securitygroup_state }}"
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      
      - name: WinRM_HTTP
        protocol: Tcp
        destination_port_range: 5985
        access: Allow
        priority: 102
        direction: Inbound

      - name: WinRM_HTTPS
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 103
        direction: Inbound

      - name: HTTP
        protocol: Tcp
        destination_port_range: 80
        access: Allow
        priority: 104
        direction: Inbound

      - name: HTTPS
        protocol: Tcp
        destination_port_range: 443
        access: Allow
        priority: 105
        direction: Inbound

      - name: RDP
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 106
        direction: Inbound

      - name: ALTHTTP
        protocol: Tcp
        destination_port_range: 8080
        access: Allow
        priority: 107
        direction: Inbound
      
- name: Add rule for custom port to {{ azure_securitygroup_name }} 
  azure_rm_securitygroup:
    resource_group: "{{ azure_resourcegroup_name }}"
    name: "{{ azure_securitygroup_name }}"
    rules:
      - name: custom_port
        protocol: Tcp
        destination_port_range: "{{ azure_securitygroup_custom_port }}"
        access: Allow
        priority: 108
        direction: Inbound
  when: azure_securitygroup_custom_port is defined and azure_securitygroup_custom_port != "" and azure_securitygroup_state == 'present'